version: '3'
services:
  db-repository:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: max
      POSTGRES_PASSWORD: jbfgslgsdlfkngd
      POSTGRES_DB: history
      POSTGRES_HOST: db-repository
      POSTGRES_PORT: 5433
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 3205:5433
    networks:
      - game-repository-network
  
  scanner-games:
    restart: always
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      POSTGRES_USER: max
      POSTGRES_PASSWORD: jbfgslgsdlfkngd
      POSTGRES_DB: history
      POSTGRES_HOST: db-repository
      POSTGRES_PORT: 5433
    depends_on:
      - db-repository
    networks:
      - game-repository-network
    
    # command: sh ./start.sh
    
  

networks:
  game-repository-network: